'use server';

import { stripe } from '@/lib/stripe';

export interface CreateCheckoutSessionResult {
  success: boolean;
  url?: string;
  error?: string;
}

export async function createCheckoutSession(
  userId: string,
  locale: string = 'en'
): Promise<CreateCheckoutSessionResult> {
  try {
    // Validate userId
    if (!userId || typeof userId !== 'string') {
      return {
        success: false,
        error: 'Invalid user ID',
      };
    }

    // Get the app URL
    const appUrl = process.env.NEXT_PUBLIC_APP_URL;
    if (!appUrl) {
      return {
        success: false,
        error: 'Configuration error: NEXT_PUBLIC_APP_URL not set',
      };
    }

    // Create Stripe Checkout Session
    const session = await stripe.checkout.sessions.create({
      mode: 'payment',
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            product_data: {
              name: 'AI Diet Plan',
              description: 'Personalized diet plan generated by AI',
            },
            unit_amount: 699, // 6.99 EUR in cents
          },
          quantity: 1,
        },
      ],
      success_url: `${appUrl}/${locale}/payment/success?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${appUrl}/${locale}/payment/cancel`,
      metadata: {
        userId,
        locale,
        productType: 'diet-plan',
      },
    });

    if (!session.url) {
      return {
        success: false,
        error: 'Failed to create checkout session URL',
      };
    }

    return {
      success: true,
      url: session.url,
    };
  } catch (error) {
    console.error('Error creating checkout session:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'An unexpected error occurred',
    };
  }
}
